import type { Product, Sale } from './types';
import { subDays, format } from 'date-fns';

const today = new Date();

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod_001',
    name: 'Canine Distemper Vaccine',
    category: 'Vaccines',
    subCategory: 'Canine',
    batchNumber: 'BATCH001',
    stockInHand: 45,
    itemsSold: 15,
    price: 25.50,
    expiryDate: '2025-08-15',
    receivedLog: [{ date: '2023-08-16', quantity: 60 }],
  },
  {
    id: 'prod_002',
    name: 'Avian Influenza Vaccine',
    category: 'Vaccines',
    subCategory: 'Poultry',
    batchNumber: 'BATCH002',
    stockInHand: 150,
    itemsSold: 50,
    price: 12.00,
    expiryDate: '2024-12-20',
    receivedLog: [{ date: '2023-06-21', quantity: 200 }],
  },
  {
    id: 'prod_003',
    name: 'Premium Dog Food (15kg)',
    category: 'Medicines & Pet Foods',
    subCategory: 'Expiry',
    batchNumber: 'BATCH003',
    stockInHand: 30,
    itemsSold: 70,
    price: 65.00,
    expiryDate: '2025-10-01',
    receivedLog: [{ date: '2023-10-02', quantity: 100 }],
  },
  {
    id: 'prod_004',
    name: 'Flea & Tick Treatment',
    category: 'Medicines & Pet Foods',
    subCategory: 'Expiry',
    batchNumber: 'BATCH004',
    stockInHand: 75,
    itemsSold: 25,
    price: 18.75,
    expiryDate: format(new Date(new Date().setDate(today.getDate() + 25)), 'yyyy-MM-dd'),
    receivedLog: [{ date: '2023-09-01', quantity: 100 }],
  },
  {
    id: 'prod_005',
    name: 'Adjustable Pet Leash',
    category: 'Accessories',
    subCategory: 'Non-expiry',
    batchNumber: 'BATCH005',
    stockInHand: 90,
    itemsSold: 10,
    price: 22.99,
    receivedLog: [{ date: '2023-07-15', quantity: 100 }],
  },
  {
    id: 'prod_006',
    name: 'Misc Livestock Antibiotic',
    category: 'Vaccines',
    subCategory: 'Misc',
    batchNumber: 'BATCH006',
    stockInHand: 200,
    itemsSold: 50,
    price: 45.00,
    expiryDate: format(new Date(new Date().setDate(today.getDate() + 10)), 'yyyy-MM-dd'),
    receivedLog: [{ date: '2023-05-20', quantity: 250 }],
  },
  {
    id: 'prod_007',
    name: 'Interactive Cat Toy',
    category: 'Accessories',
    subCategory: 'Non-expiry',
    batchNumber: 'BATCH007',
    stockInHand: 120,
    itemsSold: 30,
    price: 14.50,
    receivedLog: [{ date: '2023-11-01', quantity: 150 }],
  }
];

export const MOCK_SALES: Sale[] = [
  {
    id: 'sale_001',
    productId: 'prod_003',
    productName: 'Premium Dog Food (15kg)',
    quantity: 2,
    saleDate: format(subDays(today, 1), 'yyyy-MM-dd'),
    totalAmount: 130.00,
  },
  {
    id: 'sale_002',
    productId: 'prod_005',
    productName: 'Adjustable Pet Leash',
    quantity: 1,
    saleDate: format(subDays(today, 2), 'yyyy-MM-dd'),
    totalAmount: 22.99,
  },
  {
    id: 'sale_003',
    productId: 'prod_001',
    productName: 'Canine Distemper Vaccine',
    quantity: 5,
    saleDate: format(today, 'yyyy-MM-dd'),
    totalAmount: 127.50,
  },
  {
    id: 'sale_004',
    productId: 'prod_002',
    productName: 'Avian Influenza Vaccine',
    quantity: 10,
    saleDate: format(today, 'yyyy-MM-dd'),
    totalAmount: 120.00,
  },
  {
    id: 'sale_005',
    productId: 'prod_007',
    productName: 'Interactive Cat Toy',
    quantity: 3,
    saleDate: format(subDays(today, 4), 'yyyy-MM-dd'),
    totalAmount: 43.50,
  },
];
